/* eslint-disable @next/next/no-img-element */
import React from 'react';
import axios from 'axios';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const Table = dynamic(() => import('@/components/table'));

type E = React.FormEvent<HTMLFormElement>;

type State = {
  name: string;
  location: string;
  mobile: string;
  marks: string;
};

export default function Home() {
  const [contact, setContact] = React.useState('');
  const [state, setState] = React.useState<State | null>(null);

  const onSubmit = React.useCallback(
    async (e: E) => {
      e.preventDefault();
      const { data } = await axios.get('/api/results/' + contact);
      setState(data[0]);
      console.log(data);
      e.preventDefault();
    },
    [contact]
  );

  return (
    <>
      <Head>
        <title>Student Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="mainnav">
          <div>
            <div>
              <img
                width="10%"
                height="30%"
                src="https://www.btmofficial.org/wp-content/uploads/2023/05/bible_trust_logo_final_11-1.png"
                alt="no image"
              />
              <h1>Bible Trust Ministries</h1>
              <h3>producing future shepherds</h3>
              <p />
            </div>
          </div>
          <div className="nav">
            <a className="active" href="https://www.btmofficial.org/">
              Home
            </a>
            &nbsp;&nbsp;
            <a className="active" href="https://www.btmofficial.org/about-us/">
              About Us
            </a>
            &nbsp;&nbsp;
            <a className="active" href="http://twibs.twmglobal.org/">
              TWIBS
            </a>
            &nbsp;&nbsp;
            <a className="active" href="#about">
              Media
            </a>
            &nbsp;&nbsp;
            <a className="active" href="#donate now">
              Wings
            </a>
            &nbsp;&nbsp;
            <a
              className="active"
              href="https://www.btmofficial.org/contact-us/"
            >
              Contact Us
            </a>
          </div>
        </div>

        <br />
        <br />
        <br />
        <br />
        <br />

        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <form onSubmit={onSubmit}>
            <label htmlFor="contact">Enter Contact Number:</label>
            <input
              required
              type="text"
              id="contact"
              name="contact"
              onChange={(e) => setContact(e.target.value)}
            />
            <input type="submit" name="submit" defaultValue="Search" />
          </form>
        </div>
        <br />
        {state && <Table state={state} />}
      </>
    </>
  );
}
